site_name: TurAgencyBot
site_url: "https://wiki.tur.r6e.ru"

theme: 
  name: material
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Поменять на яркий режим

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Поменять на тёмный режим

extra_css:
  - src/stylesheets/extra.css

nav:
  - 'index.md'
  - 'tarifs.md'
  - Настройка Бота: 
    - 'settings/phrases.md'
    - 'settings/extract.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reques6e
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/reques6e
    - icon: fontawesome/brands/telegram
      link: https://t.me/travel_agency_panel_bot

copyright: Документация к боту AgencyBot
